# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets
import todos
import sqlite3
class Ui_ToDoApp(object):
    def setupUi(self, ToDoApp):
        ToDoApp.setObjectName("ToDoApp")
        ToDoApp.resize(480, 496)
        ToDoApp.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.052, y1:1, x2:0.763, y2:0.494, stop:0 rgba(204, 43, 94, 255), stop:1 rgba(117, 58, 136, 255));}")
        self.centralwidget = QtWidgets.QWidget(ToDoApp)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, -10, 191, 101))
        self.label.setStyleSheet("font: 24pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 140, 191, 51))
        self.label_2.setStyleSheet("font: 18pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 250, 141, 41))
        self.label_3.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 350, 141, 41))
        self.label_4.setStyleSheet("font: 13pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(70, 250, 401, 51))
        self.textEdit.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(70, 340, 401, 51))
        self.textEdit_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 450, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(240, 450, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.loadtodos)
        self.pushButton.clicked.connect(self.db)
        ToDoApp.setCentralWidget(self.centralwidget)
        self.retranslateUi(ToDoApp)
        QtCore.QMetaObject.connectSlotsByName(ToDoApp)
    def loadtodos(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = todos.Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def db(self):
        title = self.textEdit.toPlainText()
        desc = self.textEdit_2.toPlainText()
        conn = sqlite3.connect('mydb.db')
        cur = conn.cursor()
        cur.execute("""CREATE TABLE IF NOT EXISTS task
                               (title text, desc text)
                               """)
        cur.execute("INSERT INTO task VALUES(?,?)", (title, desc))
        conn.commit()
        cur.close()
        conn.close()

    def retranslateUi(self, ToDoApp):
        _translate = QtCore.QCoreApplication.translate
        ToDoApp.setWindowTitle(_translate("ToDoApp", "ToDoApp"))
        self.label.setText(_translate("ToDoApp", "ToDo App"))
        self.label_2.setText(_translate("ToDoApp", "Add ToDo:"))
        self.label_3.setText(_translate("ToDoApp", "Title:"))
        self.label_4.setText(_translate("ToDoApp", "Text:"))
        self.pushButton.setText(_translate("ToDoApp", "Submit"))
        self.pushButton_2.setText(_translate("ToDoApp", "Next >"))
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_ToDoApp()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())